# Generated by Django 2.1.1 on 2018-09-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('signal', models.CharField(max_length=200)),
                ('trade', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('pnl', models.FloatField(default=0)),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Algo')),
            ],
        ),
    ]
